Shopify/ruby-lsp-rails

- bin/rails
- lib/ruby_lsp/ruby_lsp_rails/rails_client.rb
- test/dummy/db/schema.rb
- test/lib/rails_client_test.rb
When we're pointing the custom bundle to the `.ruby-lsp` folder, then the project root is one folder above of it. We need to account for this when discovering the root.
I also fixed the `bin/rails` script which was broke after changing strategy to use a middleware. The schema file was changed possibly because it had some RuboCop changes. Those weren't really relevant, so I just updated to what Rails dumps for us.
> Find the correct project root when using custom bundle

- Gemfile
- Gemfile.lock
- ruby-lsp-rails.gemspec
Registering hover listeners only works starting with version 0.4.5. We need to restrict it to make sure the right version is installed.
> Restrict ruby-lsp dependency version

- lib/ruby_lsp/ruby_lsp_rails/rails_client.rb
- lib/ruby_lsp_rails/middleware.rb
- test/ruby_lsp_rails/middleware_test.rb
- test/ruby_lsp_rails/rails_client_test.rb
- test/test_helper.rb
Closes #57
Using the PID to check if the server is running is brittle - and doesn't work in the case of containers like docker. We can just use our own middleware to verify if the server is running since we know the uri and the port.
This PR changes the middleware to accept an `activate` request, which just returns `200` if the server is running.
If the activate request is taking too long to be fulfilled, then I used a timeout to cut the request short. If the request is taking long, it's likely the server is in fact running it's just being slow to respond - and we don't want to block the initialization of the Ruby LSP.
> Use middleware to check if server is running instead of checking PID

- Gemfile.lock
- lib/ruby_lsp/ruby_lsp_rails/hover.rb
- ruby-lsp-rails.gemspec
- sorbet/rbi/gems/ruby-lsp@0.5.1.rbi
- test/ruby_lsp_rails/hover_test.rb
Bump our dependency to the latest LSP version and fix the related breaking changes in how we instantiate listeners.
There are no functional changes in this PR.
> Bump to Ruby LSP v0.5.1 and fix breaking changes

- Gemfile
- Gemfile.lock
Since we already have `rubocop-shopify`, there's no need to have `rubocop`. This should result in less Dependabot notifications.
> Remove RuboCop from Gemfile

- lib/ruby_lsp/ruby_lsp_rails/extension.rb
- lib/ruby_lsp/ruby_lsp_rails/rails_client.rb
- test/ruby_lsp_rails/rails_client_test.rb
- test/test_helper.rb
There are legitimate cases why someone may want to edit code without the server running, so we want to avoid over-notifying. In this PR, we are changing the behaviour so that we output a notice in the logs, rather than showing an error dialog.
We should also update the README to explain how some features only available if the server is running, but since there is only currently one feature (Hover), it probably makes more sense to do that after Code Lens is added in https://github.com/Shopify/ruby-lsp-rails/pull/67.
Paired on with @vinistock
> Change how we warn about server not running

- README.md
Covering the new functionality added in #67.
> Update README for Code Lens features

- README.md
- lib/ruby_lsp_rails/rack_app.rb
- lib/ruby_lsp_rails/railtie.rb
- test/ruby_lsp_rails/rack_app_test.rb
By using a Rack app instead of Rails Middleware, we don't need to worry about where to insert the middleware in the stack (https://github.com/Shopify/ruby-lsp-rails/pull/89).
Apps can opt of the app with `config.ruby_lsp_rails.server = false`, while still being able to take advantage of other features of the extension.
Tophatted against Code DB and Core (with the server disabled).
Co-authored with @vinistock
> Use a Rack app instead of Rails middleware

- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
- test/ruby_lsp_rails/code_lens_test.rb
The dashboard is showing some exceptions coming through for ruby-lsp-rails on Core. Although we are unable to see the exact code in use, I was able to reproduce with a test which has a blank string as the test name. If the Code Lens requests runs before the author has typed the test name then an exception occurs.
> Fix Code Lens for test with empty string as name

- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
- test/ruby_lsp_rails/code_lens_test.rb
Closes #103
I added support only for two lines. If we were to support any number of concatenations, we'd need to use a loop that keeps checking if the `right` side of the concatenation is another concatenation, which I think is not worth the complexity. Supporting one concatenation will be enough for the majority of cases.
> Support escaped multiline strings in test names

- lib/ruby_lsp/ruby_lsp_rails/rails_client.rb
These exceptions may also happen and we want to fail gracefully if they do.
> Prevent connection reset or open timeout from raising

- Gemfile.lock
- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
- lib/ruby_lsp/ruby_lsp_rails/extension.rb
- lib/ruby_lsp/ruby_lsp_rails/hover.rb
- lib/ruby_lsp/ruby_lsp_rails/rails_client.rb
- ruby-lsp-rails.gemspec
- sorbet/rbi/gems/ruby-lsp@0.8.0.rbi
- sorbet/rbi/gems/syntax_tree@6.1.1.rbi
- sorbet/rbi/shims/uri.rbi
- test/ruby_lsp_rails/code_lens_test.rb
- test/ruby_lsp_rails/hover_test.rb
- test/ruby_lsp_rails/rack_app_test.rb
- test/ruby_lsp_rails/rails_client_test.rb
- test/test_helper.rb
Handle the breaking changes related to extension registrations and also the changes to standardize URI usages.
> Upgrade to Ruby LSP v0.8.0 and handle breaking changes

- dev.yml
- lib/ruby_lsp_rails/railtie.rb
1. We should use Ruby 3.2.2 for development.
2. Instead of requiring `rails/railtie`, which is not a valid entry point, we should just require `rails`.
- This is not an issue for our users, but it crashes `tapioca gem` because `rails/railtie` doesn't require sufficient dependencies.
> Improve development setup

- .github/workflows/ci.yml
It has proved impossible to get CI to work without removing the Gemfile.lock. Let's remove it only for Ruby 3.1 on Windows, so that our auto-merge continues to work.
> Remove Gemfile.lock when running CI on Ruby 3.1 Windows

- README.md
This is a small improvement to README.
It would be a little easier to read if the notes were in a consistent format. How about trying alerts syntax on GitHub?
- https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/
- https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts
This results in the following display:
> Improve README about NOTEs

- .github/workflows/ci.yml
- .github/workflows/publish_docs.yml
- Gemfile.lock
- dev.yml
Start using Ruby 3.3 for development/CI.
> Upgrade Ruby to 3.3

- lib/ruby_lsp_rails/rack_app.rb
- test/ruby_lsp_rails/rack_app_test.rb
Hovering on model classes like `ApplicationRecord` in a Rails application results
in raising an `ActiveRecord::TableNotSpecifiedError,` which we should be
accounting for.
Before:
```
Started GET "/ruby_lsp_rails/models/ApplicationRecord" for ::1 at 2024-02-03 08:15:12 -0600
ActiveRecord::TableNotSpecified (ApplicationRecord has no table configured. Set one with ApplicationRecord.table_name=):
...
```
After:
```
Started GET "/ruby_lsp_rails/models/ApplicationRecord" for ::1 at 2024-02-03 08:17:35 -0600
```
> Avoid inspecting schema info for abstract classes

- test/ruby_lsp_rails/addon_test.rb
Before
```
Run options: --seed 40302
..........Rails server is not running. To get Rails features in the editor, boot the Rails server
...........................
Finished in 0.654810s, 56.5049 runs/s, 241.2914 assertions/s.
```
After
```
Run options: --seed 31481
...............................
Finished in 0.664854s, 46.6268 runs/s, 206.0603 assertions/s.
```
> Fixes stdout leak in tests

- test/ruby_lsp_rails/hover_test.rb
Just a small thing I noticed when reviewing https://github.com/Shopify/ruby-lsp-rails/pull/241.
The method is `void` so we don't need to stub a return value.
(cc @gmcgibbon)
> Adjust server check stub

- Gemfile.lock
- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
- lib/ruby_lsp/ruby_lsp_rails/hover.rb
- ruby-lsp-rails.gemspec
- sorbet/rbi/gems/ruby-lsp@0.14.0.rbi
- test/ruby_lsp_rails/hover_test.rb
Based on Ruby LSP version 0.14.0, we need to update the `Hover` and `CodeLens` implementations in the Rails add-on.
These no longer extend the `Listener` class, and now use the response builder.
The associated tests have been updated, and these changes have been tested locally.
> Update Hover and CodeLens as per refactored responses in Ruby LSP

- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
- test/ruby_lsp_rails/code_lens_test.rb
Hello 👋
This is introducing code lens support for [minitest/spec](https://github.com/minitest/minitest?tab=readme-ov-file#specs-)
> Add code lens support for rails active support test cases using `minitest/spec`

- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- lib/ruby_lsp/ruby_lsp_rails/server.rb
- test/ruby_lsp_rails/hover_test.rb
- test/ruby_lsp_rails/runner_client_test.rb
- test/ruby_lsp_rails/server_test.rb
Closes https://github.com/Shopify/ruby-lsp-rails/issues/265
Currently, if we fail to initialize the server, we show errors every time hover occurs. The reason is because `initialize` raises, meaning the [memoized client](https://github.com/Shopify/ruby-lsp-rails/blob/f32f92c1bbaccae6889c13706b5de0e651335097/lib/ruby_lsp/ruby_lsp_rails/addon.rb#L17) is never set and thus causing us to try to initialized it again on every hover.
Since the client is bound to be used everywhere in this addon, I think the easiest way of handling it is falling back to a `NullClient` that simply no-ops most operations. That way, we don't have to spread a bunch of conditionals everywhere in the code.
1. On this branch, change the `Open3.popen3` command from `bin/rails` to something that doesn't exist. Like …
> Fallback to `NullClient` if initializing server fails

- Gemfile.lock
- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- ruby-lsp-rails.gemspec
- test/ruby_lsp_rails/code_lens_test.rb
- test/ruby_lsp_rails/hover_test.rb
Because of the memoized `client` method, we had a race condition. Every time someone hovered over something while the runner was still booting it would try to boot another server, since the `@client` variable was not yet set.
This PR changes the way we use client to begin initializing it with a `NullClient`. That way, features that depend on the client like hover continue to operate normally.
On `activate`, we spawn a thread that will initialize the real client concurrently. Once the thread finishes, then subsequent requests will get the information coming from the real server, without blocking any hover requests during the process.
We also need to bump the requirement on `ruby-lsp` to get https://github.com/Shopify/ruby-lsp/pull/1400 or else the `initialize` method is not invoked …
> Fix runner client race condition

- test/ruby_lsp_rails/document_symbol_test.rb
With the new Ruby LSP version, we need to ensure `initialized` ran or else the addon may not be initialized. This fixes the main build.
> Ensure addon is initiallized in document symbol test

- sorbet/rbi/shims/debug.rbi
- test/test_helper.rb
So that the debugger doesn't stop in Sorbet frames.
> Ignore sorbet paths for the debugger

- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- test/ruby_lsp_rails/runner_client_test.rb
Closes https://github.com/Shopify/ruby-lsp-rails/issues/274
I think there are two issues with the way we shutdown the server. We can't have the infinite loop checking if the thread is alive, because something might go wrong with the server and then we'll never kill the child process. I removed that loop and switched to a single sleep to give some time for the server to shutdown.
Also, I started setting the process group ID in the server process. This is a similar trick used in [spring](https://github.com/rails/spring/blob/dee217996d2377e4f50bd61399d2431dbc6566d5/lib/spring/server.rb#L88), which makes it so that if the parent process is terminated, then so will the server.
I believe these two should help with the orphaned process issues we've been seeing.
> Set process group ID in server to terminate after parent

- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- lib/ruby_lsp/ruby_lsp_rails/server.rb
- test/ruby_lsp_rails/addon_test.rb
- test/ruby_lsp_rails/hover_test.rb
- test/test_helper.rb
This change goes along with https://github.com/Shopify/ruby-lsp/pull/1464 in ruby-lsp.
Partly addresses https://github.com/Shopify/ruby-lsp-rails/issues/257
We register for changes to the schema files, and trigger a reload so as to get the latest column information. (Using the same mechanism that `reload!` in the Rails console uses).
> Add reloading for schema changes

- lib/ruby_lsp/ruby_lsp_rails/document_symbol.rb
- lib/ruby_lsp/ruby_lsp_rails/support/active_support_test_case_helper.rb
- test/dummy/app/models/user.rb
- test/ruby_lsp_rails/document_symbol_test.rb
Callbacks are ubiquitous across Rails, so it would be helpful to explicitly isolate them in the LSP via document symbols.
This approach accounts for callbacks associated with `ApplicationRecord` ([models](https://guides.rubyonrails.org/active_record_callbacks.html#available-callbacks)), `ApplicationController` ([controllers](https://api.rubyonrails.org/classes/AbstractController/Callbacks.html)), and `ApplicationJob` ([jobs](https://edgeapi.rubyonrails.org/classes/ActiveJob/Callbacks.html)).  
In addition to the various callback categories, there are 3 types of arguments to consider:
1. When the argument is a symbol (like `before_perform :foo_method`).
2. When the argument is a string (like `before_save "foo_method"`).
3. When the argument is a block (like   `before_action do ... end`). …
> Integrate document symbol for callbacks

- .rubocop.yml
- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- lib/ruby_lsp/ruby_lsp_rails/support/rails_document_client.rb
To prevent behaviour being affect by the `VERBOSE` setting, as mentioned [here](https://github.com/Shopify/ruby-lsp-rails/pull/284/files#r1517805630).
> Use `$stderr.puts` instead of `warn`

- lib/ruby_lsp/ruby_lsp_rails/document_symbol.rb
- test/dummy/app/models/user.rb
- test/ruby_lsp_rails/document_symbol_test.rb
Implements document symbol for the various types of Rails validations.
The remaining dsl feature is relationships. Based on my experience in this PR, it looks like the manner in which we handle each type of dsl feature doesn't generalize particularly cleanly. Consequently, after all the features are implemented, we can then reflect on the appropriate abstraction. Abstracting before comprehensive feature completion might cause us to create abstractions that we have to later rectify.
For now, these changes are scoped to focus on implementing validations exclusively.
> Implement document symbols for validations

- lib/ruby_lsp/ruby_lsp_rails/server.rb
Closes https://github.com/Shopify/ruby-lsp-rails/issues/289
We sometimes pass `nil` into the `params` parameter, which fails runtime type checks. We need to make it nilable to prevent this from happening.
> Fix nilable param runtime type check in server

- README.md
- lib/ruby_lsp/ruby_lsp_rails/document_symbol.rb
- test/dummy/app/models/user.rb
- test/ruby_lsp_rails/document_symbol_test.rb
Implements the document symbol for various associations supported in Rails.
Any potential refactoring can be scoped out of this for now — this PR is focused on supporting the feature.
> Implement document symbol for associations

- lib/ruby_lsp/ruby_lsp_rails/document_symbol.rb
- test/ruby_lsp_rails/document_symbol_test.rb
This changes how we display symbols for Rails macros, so that:
- It's easier to visual distinguish them from regular methods
- They are a closer represention to how the macros are typically written in code.
> Change symbol appearance for Rails macros

- .github/workflows/publish_docs.yml
Same as https://github.com/Shopify/ruby-lsp/pull/1832
> Remove Ruby version restriction for docs publishing

- Gemfile.lock
- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- lib/ruby_lsp/ruby_lsp_rails/hover.rb
- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- ruby-lsp-rails.gemspec
- sorbet/rbi/gems/ruby-lsp@0.16.0.rbi
- sorbet/tapioca/require.rb
- test/ruby_lsp_rails/code_lens_test.rb
- test/ruby_lsp_rails/definition_test.rb
- test/ruby_lsp_rails/document_symbol_test.rb
- test/ruby_lsp_rails/hover_test.rb
- test/test_helper.rb
Needed due to https://github.com/Shopify/ruby-lsp/pull/1648
> Update for latest ruby-lsp changes

- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
- test/ruby_lsp_rails/code_lens_test.rb
Some tests use classes instead of modules for namespacing, such us:
```ruby
module Foo
class Bar
class MyTest < ActiveSupport::TestCase
test "something" do
end
end
end
end
```
And when this happens, the current implementation would still push the group id to the stack, which would cause the first test group (`MyTest`) to already have non-nil group id. This will make the extension to think there's another parent test group, which is not the case and will cause no code lens to be shown.
This commit fixes this by not pushing the group id to the stack when encountering non-test classes, and only pop the group id when the encountered class is a test class.
> Don't push group id to stack when encountering non-test classes

- lib/ruby_lsp/ruby_lsp_rails/hover.rb
- lib/ruby_lsp/ruby_lsp_rails/server.rb
- test/dummy/app/models/composite_primary_key.rb
- test/dummy/db/migrate/20240403145625_create_composite_pk.rb
- test/dummy/db/schema.rb
- test/ruby_lsp_rails/hover_test.rb
Closes #313
Rails 7.1 supports composite primary keys so the return type will either be a string or an array of strings, depending on the pk type. I've added a test for that case.
I was a bit surprised that the tests don't go through `resolve_database_info_from_model`. I guess because it would involve the runner and require db setup? Anyways, I tested it manually and this is what it looks like:
> Add primary key indicator to model hover response

- lib/ruby_lsp/ruby_lsp_rails/server.rb
- test/ruby_lsp_rails/server_test.rb
I'm not exactly sure how it was triggered, but I had crash for this:
```
undefined method `<' for an instance of T::Private::Types::TypeAlias (NoMethodError)
```
I'll add a test if I'm able to reproduce.
> Prevent crash during ActiveRecord const check

- lib/ruby_lsp/ruby_lsp_rails/addon.rb
Prevent `VERSION` wrongly resolving to the one from ruby-lsp: https://github.com/Shopify/ruby-lsp/blob/main/lib/ruby-lsp.rb
> Fix version logging

- Gemfile.lock
- ruby-lsp-rails.gemspec
- sorbet/rbi/gems/ruby-lsp@0.16.5.rbi
- test/ruby_lsp_rails/code_lens_test.rb
Since https://github.com/Shopify/ruby-lsp/pull/1896 the testing framework for rails is dependant on the presence on `bin/rails`.
For https://github.com/Shopify/ruby-lsp-rails/pull/341 I need to bump the minimum required `ruby-lsp` but tests are failing due to the above PR, so I fix them here in a separate PR.
> Update tests for `ruby-lsp` changes

- .gitignore
- .rubocop.yml
- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- lib/ruby_lsp/ruby_lsp_rails/server.rb
For if we decide to go with this option (see discussion in issue).
Closes https://github.com/Shopify/ruby-lsp-rails/issues/336
> Remove Sorbet from `server.rb`

- .github/workflows/ci.yml
- README.md
- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- lib/ruby_lsp/ruby_lsp_rails/definition.rb
- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- lib/ruby_lsp/ruby_lsp_rails/server.rb
- test/dummy/app/controllers/application_controller.rb
- test/dummy/config/initializers/action_dispatch.rb
- test/dummy/config/routes.rb
- test/ruby_lsp_rails/definition_test.rb
- test/ruby_lsp_rails/server_test.rb
This PR adds support for the Definition request for Rails routes.
The implementation is based on @tenderlove's prototype in https://github.com/tenderlove/refreshing, and uses the behaviour added by @luanzeba and others in https://github.com/rails/rails/pull/47877.
Notes:
- For Sorbet projects using the Tapioca DSL generators for routes, the Definition Lookup will return two results - one for the RBI file, and one for the actual route.
- Unfortunately it doesn't work on Core, the source location always point to a `super` call in `routing_annotations.rb`. `bin/rails routes --expanded` has the same problem.
- There is some behaviour that might be a bug in VS Code:
If you double-click on a route name to select it, then choose Go To Definition, it works _only_ if the token has parenthesis on …
> Add Definition support for routes

- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- test/ruby_lsp_rails/definition_test.rb
This was supposed to be in https://github.com/Shopify/ruby-lsp-rails/pull/331 but I think was accidentally lost in a rebase.
> Fix thread handling

- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- gemfiles/Gemfile-rails-main
- lib/ruby_lsp/ruby_lsp_rails/hover.rb
- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- test/ruby_lsp_rails/code_lens_test.rb
- test/ruby_lsp_rails/hover_test.rb
- test/ruby_lsp_rails/runner_client_test.rb
Closes https://github.com/Shopify/ruby-lsp-rails/issues/351 but we still need to address https://github.com/Shopify/ruby-lsp-rails/issues/348.
> Fix CI setup for Windows

- .github/workflows/ci.yml
The tests are the most likely thing to fail, so let's run those first, so we get earlier feedback.
> Re-order CI steps

- test/dummy/app/models/membership.rb
- test/dummy/app/models/organization.rb
- test/dummy/app/models/user.rb
- test/dummy/db/migrate/20240503152928_create_organizations.rb
- test/dummy/db/migrate/20240503153021_create_memberships.rb
- test/dummy/db/schema.rb
To help with manually testing https://github.com/Shopify/ruby-lsp-rails/issues/358
> Add a `has_many through` association to the dummy app

- .github/workflows/ci.yml
- Rakefile
The first time someone cloned and runs the tests, they'll get a confusing error because the dB doesn't yet exist.
I originally considered checking if the DB exists first, but creating is very quick so I don't think that's necessary.
(for sqlite3 at least, `db:setup` is idempotent so there's no problem with it being re-run. We don't care about the data in the DB).
> Set up DB for tests as part of default Rake task

- lib/ruby_lsp/ruby_lsp_rails/server.rb
The tests against Rails main are currently failing.
Closes https://github.com/Shopify/ruby-lsp-rails/issues/378
> Eager load routes if necessary

- .github/workflows/ci.yml
Ruby 3.0 is EOL as of 23 Apr 2024
We already dropped in ruby-lsp: https://github.com/Shopify/ruby-lsp/pull/2017
> Drop Ruby 3.0 in CI

- Gemfile.lock
- ruby-lsp-rails.gemspec
Since we already depend on `sorbet-runtime` via `ruby-lsp`, I don't think there's any need to have it here.
> Remove explicit dependence on sorbet-runtime

- lib/ruby_lsp/ruby_lsp_rails/definition.rb
- test/ruby_lsp_rails/definition_test.rb
We made an [addition](https://github.com/Shopify/ruby-lsp/pull/2115/files) to Ruby LSP which to add call node information to `NodeContext`. This means we can now fix the Ruby LSP Rails beahavior for various DSL calls.
For example, previously when you had an association `has_many :widgets`, the Go To Definition feature would only work if triggered on the `has_many` token. Now it works for the `:widgets` token, as originally intended.
> Use NodeContext from RubyLSP to fix Definition targetting

- lib/ruby_lsp/ruby_lsp_rails/support/callbacks.rb
See https://guides.rubyonrails.org/active_record_callbacks.html#aliases-for-after-commit
> Recognize aliases for `after_commit`

- README.md
- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
- test/ruby_lsp_rails/code_lens_test.rb
Closes https://github.com/Shopify/ruby-lsp-rails/issues/51
Adds code lens to run migrations to specific versions in the terminal. This is convenient because it allows developers to quickly rollback or fast-forward to specific schema versions with a click.
> Add code lens for running migrations

- README.md
- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- lib/ruby_lsp/ruby_lsp_rails/server.rb
- test/dummy/app/controllers/users_controller.rb
- test/ruby_lsp_rails/code_lens_test.rb
- test/ruby_lsp_rails/server_test.rb
Part of  https://github.com/Shopify/ruby-lsp-rails/issues/50
Adds code lens to find routes in the routes file based on a given controller action. You need to grep bin/rails routes for this information manually. If Rails already knows this info, we should make it more easily accessible.
> Add code lens for mapping actions to routes

- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
If for any reason the server died and the pipes are broken, we cannot keep trying to write to STDIN or read from STDOUT because that will raise and halt the regular operation of the LSP.
> Prevent broken pipes leading to client errors

- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
- test/ruby_lsp_rails/code_lens_test.rb
We cannot assume that there will always be something in the class stack, because the user could be editing a method on the top level.
> Fix route code lens when there are no classes in the stack

- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
- test/ruby_lsp_rails/code_lens_test.rb
Closes #409
Move the test library check only before trying to create new test code lenses, so that the others are still displayed.
> Check test framework only before pushing test code lens

- Gemfile.lock
- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- lib/ruby_lsp/ruby_lsp_rails/server.rb
- test/dummy/app/views/users/index.html.erb
- test/ruby_lsp_rails/code_lens_test.rb
Closes #384
This PR adds the ability to jump to related views from a controller action.
Implementation:
1. Updated the `ruby-lsp` just to get proper ERB support
2. Started returning the `Rails.root` from the server initialization response. We often need to know where the application exists from the addon side
3. Used the Root and the controller information to discover which views exist for a given action
https://github.com/user-attachments/assets/5d63445c-4352-47fb-aa3a-76ad45243c74
> Add jump to view code lenses

- lib/ruby_lsp/ruby_lsp_rails/definition.rb
Once https://github.com/Shopify/ruby-lsp/pull/2028 is released, we should no longer be limited to the current file.
cc @aryan-soni, thought would be happy to see since you were the original author.
> Update docs for improved Definition behaviour

- .github/workflows/ci.yml
- Gemfile.lock
Since we dropped Ruby 3.0 this seems no longer necessary.
> No need to delete `Gemfile.lock` in CI for Windows

- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
If the server has died (e.g. after running for a long time) then an `IOError` may occur while trying to shut it down.
> Rescue `IOError` during shutdown

- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- test/ruby_lsp_rails/runner_client_test.rb
> Fix `NullClient#send_notification`

- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
I noticed this was messed up on https://shopify.github.io/ruby-lsp-rails/RubyLsp/Rails/CodeLens.html
> Fix markdown in Code Lens docs

- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
- test/ruby_lsp_rails/code_lens_test.rb
We're currently always running the entire file when you have multiple test classes in the same one. We should use the same name regex existing in the Ruby LSP to properly filter the exact class being executed.
I just brought the approach over and added a test.
> Use regex to filter test runs for multiple classes in the same file

- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
Our code lens code assumes that migration files are already saved to disk, by running `File.basename(T.must(@path))`.
It seemed like a reasonable assumption, but judging by our error telemetry, it seems people will write unsaved migrations more often that I expected. We can't run a migration that wasn't saved yet, so we just need to ensure the code doesn't break.
**Note**: there's currently no way to test this because the `with_server` test helper assumes that the URI passed will exist on disk, which is a limitation of our helper. This means I can't pass an `untitled:Untitled-1` URI to reproduce the issue.
You can verify that the issue is fixed after this change by pasting this migration into an unsaved file.
```ruby
class CreateUsers < ActiveRecord::Migration[7.0]
def change …
```
> Prevent migration code lens from failing in unsaved files

- lib/ruby_lsp/ruby_lsp_rails/server.rb
- test/ruby_lsp_rails/server_test.rb
Similar to what we already done for Ruby LSP, we can restructure things to avoid the need for the artificial 'void' concept.
> Avoid need for special VOID return

- .github/workflows/ci.yml
> Stop testing against Ruby 3.1 in CI

- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
- test/ruby_lsp_rails/code_lens_test.rb
Closes https://github.com/Shopify/ruby-lsp-rails/issues/463
> Skip directories for view paths

- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- test/ruby_lsp_rails/runner_client_test.rb
Ideally, add-ons shouldn't be calling `send_notification` or `make_request` directly. Let's provide a nicer API.
Also, I changed `params` to be a keyword splat since that makes the API more intuitive.
> Add API for delegate notifications and requests

- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- lib/ruby_lsp/ruby_lsp_rails/server.rb
- test/ruby_lsp_rails/runner_client_test.rb
- test/ruby_lsp_rails/server_test.rb
I can be difficult to debug what's happening in the server or in a server add-on. I propose we make the stderr pipe as the means for the runtime server to send debug messages.
By dedicating a pipe exclusively for this, there's fewer risks of messing up with actual request/response cycles and we can easily print it asynchronously by adding a thread worker.
> Allow server to print debug messages

- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- test/ruby_lsp_rails/launch_test.rb
- test/ruby_lsp_rails/runner_client_test.rb
- test/test_helper.rb
We are currently raising if something is printed to stdout from the server and it results in an empty message, but I'm not sure why we were raising in the first place.
This keeps filling up our telemetry with errors that aren't actionable. It could be that the application printed something, but since there's no content, I think it's okay to just return `nil` (since this method is already expected to be able to return `nil`).
> Return `nil` on empty response

- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- lib/ruby_lsp/ruby_lsp_rails/server.rb
- test/ruby_lsp_rails/server_test.rb
Add the ability to check for pending migrations and run them through the Rails runner client.
For checking if something is pending, we use the Rails API directly, which raises if there are any pending migrations.
For running them, we can't do it in process. The code that runs migrations is not designed to be invoked repeatedly and uses `load`, which means that we could end up with a memory bloat. I used `Open3.capture2` to run in a child process and grab the results.
> Add support for checking for pending migrations and running them

- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- test/ruby_lsp_rails/addon_test.rb
- test/test_helper.rb
Check for pending migrations, notify the user and offer to run them. The idea is that if any modifications are made to the `db/migrate` directory, we check if there are pending migrations.
If there are, we show a dialog and offers to run them. If the user decides to do it, we then fire a request to the server to run the migrations.
Note: we only show the dialog if a migration is deleted or created, otherwise it can become really annoying when you are editing the migration you just created.
> Check for pending migrations when watcher is fired

- lib/ruby_lsp/ruby_lsp_rails/hover.rb
We cannot use `present?` in the add-on side of the code because that method is defined by `activesupport` and that gem is not required on the LSP side.
It's only safe to use it in the runtime server side. This is currently breaking hover.
Note: tests won't catch this because in tests the Rails context is loaded through the dummy application, which makes tests pass despite this code breaking every time in real scenarios.
> Remove usage of present? from hover

- lib/ruby_lsp/ruby_lsp_rails/server.rb
- test/ruby_lsp_rails/server_test.rb
Closes https://github.com/Shopify/ruby-lsp-rails/issues/516
This change allows Ruby LSP to stay alive even if an error occurred when trying to connect to the database.
I also added a specific `rescue` for `ActiveRecord::NoDatabaseError` since this could be a common problem. Without that, users would see a very long stacktrace in the logs.
It may _partially_ help with https://github.com/Shopify/ruby-lsp/issues/2838 too.
> Improve error handling for database problems

- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
Closes https://github.com/Shopify/ruby-lsp-rails/issues/519
> Improve diagnostics for situations where Rails fails to boot

- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
`Errno::ENOENT` already inherits from `StandardError`, so there is no need to rescue it explicitly
```
> Errno::ENOENT.new.is_a?(StandardError)
=> true
```
> Remove redundant rescue in runner client

- .vscode/settings.json
- lib/ruby_lsp/ruby_lsp_rails/server.rb
- test/ruby_lsp_rails/server_test.rb
Closes https://github.com/Shopify/ruby-lsp/issues/2886
We cannot use blanket rescue statements for the entire server because the behaviour for handling errors is different between requests and notifications.
For requests, we want to return `error: message` instead of the typicaly `result: something`. And for notifications, we cannot return anything, we can only log that an error occurred.
The approach that I took here is to create handlers that we can use both ourselves and in server add-ons, that provide appropriate error handling for requests or notifications.
I also created convenience  methods for returning responses or errors.
> Unify all error handling for the server

- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- lib/ruby_lsp/ruby_lsp_rails/completion.rb
- test/ruby_lsp_rails/completion_test.rb
Closes: https://github.com/Shopify/ruby-lsp-rails/issues/369
Adding ActiveRecord `.where` completion suggestions.
I've chosen to only provide suggestions once the user begins typing the name of the column to filter by. This is slightly different than the spec in the ticket. I don't think the call_node_enter listener can be used if suggestions are to be provided before the user begins typing a column name.
Happy to investigate this further! But I think this can be added as a follow up in another PR since the approach for when to begin suggesting seems like it should be different.
Here are some videos of how this looks!
https://github.com/user-attachments/assets/e70bd663-41f5-42b3-bfc6-94f918ff05fc
https://github.com/user-attachments/assets/d22bc44e-d9fd-4f97-bfe5-e73e31cdfba2
> Completion for Active Record .where queries

- lib/ruby_lsp/ruby_lsp_rails/server.rb
I noticed that we were spending a lot of time doing file IO operations coming from the listen gem. After some investigation, these appear to be coming from Rails' own file watching mechanisms, which spawn threads that will check if views are being modified to trigger rendering or reloading in the background.
We currently don't have any functionality that depends on views being rendered. Additionally, the LSP already watches files, so even if we wanted to trigger view rendering, the language server would be in a better position to dictate which views to reload.
This PR shuts down view file watching, which eliminates a good chunk of overhead that we were seeing in the Tapioca add-on.
I initially tried setting `config.file_watcher` to a no-op implementation, but that doesn't work. The reason …
> Reduce file watching overhead from Rails

- lib/ruby_lsp/ruby_lsp_rails/addon.rb
This is to support https://github.com/Shopify/tapioca/pull/2150 but will probably be useful for other upcoming features.
> Watch for YAML file changes for fixtures

- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- lib/ruby_lsp/ruby_lsp_rails/server.rb
- test/ruby_lsp_rails/runner_client_test.rb
- test/ruby_lsp_rails/server_test.rb
Previously, we were only allowing the server and its runtime add-ons to send simple strings to the stderr pipe, which would become log notifications.
To support initiating progress from the server, we will need to allow any type of LSP notification to be send asynchronously.
This PR changes our current logger thread to become a more general notifier thread, which will read any messages received from the server and push them to the outgoing queue.
To prevent creating a breaking change, I kept the `log_message` method, but changed it to build the right notification expected.
> Allow server to send asynchronous notifications to client

- lib/ruby_lsp/ruby_lsp_rails/server.rb
One of the slowest parts of DSL RBI generation in the Tapioca add-on is actually the fact that we're reloading the Rails app.
In addition to adding progress notifications there, let's also show the progress of reloading the app, so that the user knows what's going on.
> Show progress when reloading the Rails application

- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- test/ruby_lsp_rails/addon_test.rb
Closes #540
Allow disabling the pending migration prompt through an addon setting. To disable, users can add this to their configuration:
```json
"rubyLsp.addonSettings": {
"Ruby LSP Rails": {
"enablePendingMigrationsPrompt": false
}
}
```
> Allow disabling pending migration prompt

- test/ruby_lsp_rails/runner_client_test.rb
The default values behavior changed in https://github.com/rails/rails/pull/54683
> Fix tests for Rails main due to changes relating to default column value 

- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- lib/ruby_lsp/ruby_lsp_rails/rails_test_style.rb
- test/ruby_lsp_rails/rails_test_style_test.rb
Closes https://github.com/Shopify/ruby-lsp/issues/3179, closes https://github.com/Shopify/ruby-lsp/issues/3170
This PR builds on #591’s test discovery support by generating test commands for Rails tests discovered in VS Code’s Test Explorer.
**Before** 
Tests defined via `test "…"` appeared in the explorer, but clicking _Run_ did nothing as no command was emitted.
**After**
Now clicking _Run_ emits the exact `bin/rails test …` command Rails uses at runtime.
Added command resolution for:
- Directories: `Dir.glob` on `*_test.rb/test_*.rb`
- Files: individual test files
- Groups: named groups via `--name "/GroupTest(#|::)/"`
- Methods: single tests as `file:line` entries
For this to work, we normalize string-based test names (e.g., `"should do something"`) by prefixing `test_` and replacing …
> Add Rails test command resolution

- lib/ruby_lsp/ruby_lsp_rails/rails_test_style.rb
- test/fixtures/test_with_escaped_quotes.rb
- test/ruby_lsp_rails/rails_test_style_test.rb
I found a bug while doing early testing of the explorer functionality in some Rails apps. We were having a test item ID mismatch (between discovered vs reported during execution) for tests that include a backslash.
If we have this scenario
```ruby
class MyTest < ActiveSupport::TestCase
test "something \"escaped\"" do
end
end
```
Prism reports the string node's content to be `something \\\"escaped\\\"`, which is the escaped version of the content (both the quote and the backslash itself are escaped).
We need to use `unescaped` to get the actual string without the extra escaping, so that we match the same ID reported during test execution.
> Strip extra backslashes from discovered test names

- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
- lib/ruby_lsp/ruby_lsp_rails/completion.rb
- lib/ruby_lsp/ruby_lsp_rails/definition.rb
- lib/ruby_lsp/ruby_lsp_rails/document_symbol.rb
- lib/ruby_lsp/ruby_lsp_rails/hover.rb
- lib/ruby_lsp/ruby_lsp_rails/rails_test_style.rb
- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- lib/ruby_lsp/ruby_lsp_rails/server.rb
- lib/ruby_lsp/ruby_lsp_rails/support/active_support_test_case_helper.rb
- lib/ruby_lsp/ruby_lsp_rails/support/associations.rb
- lib/ruby_lsp/ruby_lsp_rails/support/callbacks.rb
- sorbet/config
- test/ruby_lsp_rails/addon_test.rb
- test/ruby_lsp_rails/runner_client_test.rb
- test/test_helper.rb
The changes in #585 were causing our tests to hang, so I reverted them as part of #599.
Thankfully, we no longer need those checks, now that we can fully migrate to the new RBS in comments syntax.
This PR fully moves the Rails add-on to use only comments, removing its need for the Sorbet runtime.
Once the Ruby LSP itself drops its need for the runtime, we can switch from using `sorbet-static-and-runtime` to just `sorbet-static`.
> Migrate to RBS in comments syntax

- lib/ruby_lsp/ruby_lsp_rails/addon.rb
- lib/ruby_lsp/ruby_lsp_rails/rails_test_style.rb
This parameter is not used for anything, so we can remove it.
> Remove unused runner client parameter from RailsTestStyle

- .rubocop.yml
[Realease 0.7.0](https://github.com/rubocop/rubocop-rake/releases/tag/v0.7.0) pluginified rubocop rake. This PR removes the deprecation warning by changing to the plugin syntax in `.rubocop.yml`.
> Change rubocop rake to plugin

- lib/ruby_lsp/ruby_lsp_rails/rails_test_style.rb
- test/ruby_lsp_rails/rails_test_style_test.rb
I introduced an issue in #612. I forgot to invoke `super` for the module event, which means we stopped tracking the right module nesting.
This PR just adds the missing `super` call with a test to prevent another regression.
> Ensure we're keeping track of module nesting

- lib/ruby_lsp/ruby_lsp_rails/rails_test_style.rb
Somehow, we're seeing a race condition of the listener receiving events before it is fully initialized. Let's ensure that we create the stack before invoking super.
> Create parent stack before invoking super

- lib/ruby_lsp/ruby_lsp_rails/server.rb
We were only rescuing StandardError's but we can also rescue some of the Exception class descendants
> Rescue more exceptions in error handlers

- .rubocop.yml
Addresses:
```
rubocop-sorbet extension supports plugin, specify `plugins: rubocop-sorbet` instead of `require: rubocop-sorbet` in /Users/joshuayoung/Projects/Shopify/ruby-lsp-rails/.rubocop.yml.
For more information, see https://docs.rubocop.org/rubocop/plugin_migration_guide.html.
```
> Use rubocop-sorbet as plugin

- lib/ruby_lsp/ruby_lsp_rails/definition.rb
- lib/ruby_lsp/ruby_lsp_rails/hover.rb
- lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
- lib/ruby_lsp/ruby_lsp_rails/server.rb
- test/ruby_lsp_rails/hover_test.rb
- test/ruby_lsp_rails/server_test.rb
Closes #476 
Add class information on hover in the associations for models. 
We provide the same information that hover on constants provide, but in the symbol of the associations.
> Add hover information on associations

- lib/ruby_lsp/ruby_lsp_rails/rails_test_style.rb
- test/ruby_lsp_rails/rails_test_style_test.rb
We were using the formatted example descriptions as both the ID and the label. That's not the best because it doesn't match what the user wrote (with spaces and as plain text) and also ends up requiring folks to add underscores for filtering examples.
This PR starts using the unformatted names as labels, which better matches the structure of the file. Note that labels are only used for presentation and filtering in the UI, we rely on the IDs for the actual running functionality.
> Use unformatted descriptions as test example labels
